modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "equivalentexchange"
version = "${version}"
displayName = "Equivalent Exchange 4"
authors = "CreeperHost"
description = '''
'''
#logoFile = ""

[[dependencies.equivalentexchange]]
modId = "neoforge"
type="required"
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.equivalentexchange]]
modId = "minecraft"
type="required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.equivalentexchange]]
modId = "architectury"
type="required"
versionRange = "[11.0.11,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.equivalentexchange]]
modId = "polylib"
type="required"
versionRange = "[2004.0.3,)"
ordering = "AFTER"
side = "BOTH"

